[keyboard]
name = "ble-test2"
product_name = "ble-test2"
vendor_id = 0x4e4b
product_id = 0x4649
manufacturer = "RMK"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P0_24", "P0_13", "P1_06", "P0_10"] # , "P0_10","P0_09"
output_pins = ["P1_11", "P1_10", "P0_03"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation.
# Checkout doc here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
# row2col = true

[layout]
rows = 4
cols = 3
layers = 2
keymap = [
    [
        ["A", "B", "C"],
        ["Kc1", "Kc2", "Kc3"],
        ["LCtrl", "MO(1)", "LShift"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)"]
    ],
    [
        ["TO(1)", "TT(1)", "TG(2)"],
        ["DF(1)", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"]
    ],
]


[ble]
enabled = true
# vddh has an internal voltage divider
# battery_adc_pin = "vddh"
# Or
 battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806

 charge_state.pin = "P0_07"
 charge_state.low_active = true
 charge_led.pin = "P0_05"
 charge_led.low_active = false
